# Generated by Django 2.2.5 on 2019-09-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='users',
            new_name='user',
        ),
    ]
