# Generated by Django 2.2.5 on 2019-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190922_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
