# Generated by Django 2.2.5 on 2019-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('users', '0004_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metrics',
            field=models.ManyToManyField(to='metrics.Metric'),
        ),
    ]
